const mongoose= require('mongoose');
const contactSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true    
    },
    dateOfBirth:{
        type:String,
        default:'',
    },
    mainMobileNumber:{
        type:Number,
        required:true,
        unique:true
    },
    alternateMobileNumbers:[{
        type:Number,
        default:''
    }],
    mainEmail:{
        type:String,
        required:true
    },
    alternateEmails:[{
        type:String,
        default:''
    }],
    date:{
        type:Date,
        default:Date.now()
    }
});
module.exports=mongoose.model('Contact',contactSchema);